[package]
name = "anylang"
version = "0.0.0"
edition = "2024"
authors = ["puffy_with_eyes"]
repository = "https://github.com/PuffyWithEyes/anylang"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
syn = { version = "*", features = ["full"] }
quote = "*"
serde_json = { version = "*", optional = true }
proc-macro2 = "*"


[features]
default = ["json"]
json = ["serde_json"]
